# run: conda env create --file environment.yml
name: hf2020_sem04_da
channels:
- conda-forge
dependencies:
- python=3.7
- numpy=1.18.1
- scipy=1.4.1
- pandas=1.1.0
- matplotlib=3.1.3
- seaborn=0.10.0
- ipython=7.12.0
- notebook=6.0.3
- pip=18.0
- cython=0.28.4
- geopandas=0.8.0
- descartes=1.1.0
- mapclassify=2.3.0
